
CREATE TABLE IF NOT EXISTS entrenador (
  Nick VARCHAR(20) PRIMARY KEY NOT NULL DEFAULT 'Ash Ketpchup',
  Nombre VARCHAR(100) NOT NULL,
  -- Genero VARCHAR(20) NOT NULL,
  Exp INT(5) NOT NULL,
  Nivel INT(5) NOT NULL,
  ContenedorExp INT(5) NOT NULL,
  PokeBalls INT(5) NOT NULL,
  SuperBalls INT(5) NOT NULL,
  UltraBalls INT(5) NOT NULL,
  MasterBalls INT(5) NOT NULL);
  
CREATE TABLE IF NOT EXISTS atrapado(
  numero_nacional VARCHAR(3) PRIMARY KEY NOT NULL,
  numero_regional VARCHAR(3) NOT NULL,
  region VARCHAR(20) NOT NULL,
  nombre VARCHAR(20) NOT NULL,
  tipoUno VARCHAR(10) NOT NULL,
  tipoDos VARCHAR(10) DEFAULT 'vacio',
  genero VARCHAR(6) DEFAULT 'hembra',
  descripcion VARCHAR(150) DEFAULT 'vacio',
  numeroEvolucion INT(1) NOT NULL,
  nivelEvolucion INT(3) NOT NULL,
  evoluciona VARCHAR(3) NOT NULL,
  nivel INT(3) DEFAULT 1,
  experiencia INT(3) DEFAULT 0,
  ContenedorExp INT(3) DEFAULT 5,
  hp INT(4) DEFAULT 100,
  hp_max INT(4) DEFAULT 100,
  ataque INT(4) DEFAULT 5,
  defensa INT(4) DEFAULT 5,
  ataque_especial INT(4) DEFAULT 5,
  defensa_especial INT(4) DEFAULT 5,
  velocidad INT(4) DEFAULT 5,
  estado VARCHAR(15) DEFAULT 'nada',
  IV INT(3) DEFAULT 31,
  EV INT(3) DEFAULT 254,
  capturado INT(10) DEFAULT 0,
  favorito VARCHAR(10) DEFAULT 0,
  ball VARCHAR(10) DEFAULT 'vacio');
  
CREATE TABLE IF NOT EXISTS equipo(
  numero_nacional VARCHAR(3) PRIMARY KEY NOT NULL,
  numero_regional VARCHAR(3) NOT NULL,
  region VARCHAR(20) NOT NULL,
  nombre VARCHAR(20) NOT NULL,
  tipoUno VARCHAR(10) NOT NULL,
  tipoDos VARCHAR(10) DEFAULT 'vacio',
  genero VARCHAR(6) DEFAULT 'hembra',
  descripcion VARCHAR(150) DEFAULT 'vacio',
  numeroEvolucion INT(1) NOT NULL,
  nivelEvolucion INT(3) NOT NULL,
  evoluciona VARCHAR(3) NOT NULL,
  nivel INT(3) DEFAULT 1,
  experiencia INT(3) DEFAULT 0,
  ContenedorExp INT(3) DEFAULT 5,
  hp INT(4) DEFAULT 100,
  hp_max INT(4) DEFAULT 100,
  ataque INT(4) DEFAULT 5,
  defensa INT(4) DEFAULT 5,
  ataque_especial INT(4) DEFAULT 5,
  defensa_especial INT(4) DEFAULT 5,
  velocidad INT(4) DEFAULT 5,
  estado VARCHAR(15) DEFAULT 'nada',
  IV INT(3) DEFAULT 31,
  EV INT(3) DEFAULT 254,
  capturado INT(10) DEFAULT 0,
  favorito VARCHAR(10) DEFAULT 0,
  ball VARCHAR(10) DEFAULT 'vacio');

CREATE TABLE IF NOT EXISTS nacional(
  numero_nacional VARCHAR(3) PRIMARY KEY NOT NULL,
  numero_regional VARCHAR(3) NOT NULL,
  region VARCHAR(20) NOT NULL,
  nombre VARCHAR(20) NOT NULL,
  tipoUno VARCHAR(10) NOT NULL,
  tipoDos VARCHAR(10) DEFAULT 'vacio',
  genero VARCHAR(6) DEFAULT 'hembra',
  descripcion VARCHAR(150) DEFAULT 'vacio',
  numeroEvolucion INT(1) NOT NULL,
  nivelEvolucion INT(3) NOT NULL,
  evoluciona VARCHAR(3) NOT NULL,
  nivel INT(3) DEFAULT 1,
  experiencia INT(3) DEFAULT 0,
  ContenedorExp INT(3) DEFAULT 5,
  hp INT(4) DEFAULT 100,
  hp_max INT(4) DEFAULT 100,
  ataque INT(4) DEFAULT 5,
  defensa INT(4) DEFAULT 5,
  ataque_especial INT(4) DEFAULT 5,
  defensa_especial INT(4) DEFAULT 5,
  velocidad INT(4) DEFAULT 5,
  estado VARCHAR(15) DEFAULT 'nada',
  IV INT(3) DEFAULT 31,
  EV INT(3) DEFAULT 254,
  capturado INT(10) DEFAULT 0,
  favorito VARCHAR(10) DEFAULT 0,
  ball VARCHAR(10) DEFAULT 'vacio');
  
CREATE TABLE IF NOT EXISTS kanto(
  numero_nacional VARCHAR(3) PRIMARY KEY NOT NULL,
  numero_regional VARCHAR(3) NOT NULL,
  region VARCHAR(20) NOT NULL,
  nombre VARCHAR(20) NOT NULL,
  tipoUno VARCHAR(10) NOT NULL,
  tipoDos VARCHAR(10) DEFAULT 'vacio',
  genero VARCHAR(6) DEFAULT 'hembra',
  descripcion VARCHAR(150) DEFAULT 'vacio',
  numeroEvolucion INT(1) NOT NULL,
  nivelEvolucion INT(3) NOT NULL,
  evoluciona VARCHAR(3) NOT NULL,
  nivel INT(3) DEFAULT 1,
  experiencia INT(3) DEFAULT 0,
  ContenedorExp INT(3) DEFAULT 5,
  hp INT(4) DEFAULT 100,
  hp_max INT(4) DEFAULT 100,
  ataque INT(4) DEFAULT 5,
  defensa INT(4) DEFAULT 5,
  ataque_especial INT(4) DEFAULT 5,
  defensa_especial INT(4) DEFAULT 5,
  velocidad INT(4) DEFAULT 5,
  estado VARCHAR(15) DEFAULT 'nada',
  IV INT(3) DEFAULT 31,
  EV INT(3) DEFAULT 254,
  capturado INT(10) DEFAULT 0,
  favorito VARCHAR(10) DEFAULT 0,
  ball VARCHAR(10) DEFAULT 'vacio');
  
CREATE TABLE IF NOT EXISTS johto(
  numero_nacional VARCHAR(3) PRIMARY KEY NOT NULL,
  numero_regional VARCHAR(3) NOT NULL,
  region VARCHAR(20) NOT NULL,
  nombre VARCHAR(20) NOT NULL,
  tipoUno VARCHAR(10) NOT NULL,
  tipoDos VARCHAR(10) DEFAULT 'vacio',
  genero VARCHAR(6) DEFAULT 'hembra',
  descripcion VARCHAR(150) DEFAULT 'vacio',
  numeroEvolucion INT(1) NOT NULL,
  nivelEvolucion INT(3) NOT NULL,
  evoluciona VARCHAR(3) NOT NULL,
  nivel INT(3) DEFAULT 1,
  experiencia INT(3) DEFAULT 0,
  ContenedorExp INT(3) DEFAULT 5,
  hp INT(4) DEFAULT 100,
  hp_max INT(4) DEFAULT 100,
  ataque INT(4) DEFAULT 5,
  defensa INT(4) DEFAULT 5,
  ataque_especial INT(4) DEFAULT 5,
  defensa_especial INT(4) DEFAULT 5,
  velocidad INT(4) DEFAULT 5,
  estado VARCHAR(15) DEFAULT 'nada',
  IV INT(3) DEFAULT 31,
  EV INT(3) DEFAULT 254,
  capturado INT(10) DEFAULT 0,
  favorito VARCHAR(10) DEFAULT 0,
  ball VARCHAR(10) DEFAULT 'vacio');
  
CREATE TABLE IF NOT EXISTS hoenn(
  numero_nacional VARCHAR(3) PRIMARY KEY NOT NULL,
  numero_regional VARCHAR(3) NOT NULL,
  region VARCHAR(20) NOT NULL,
  nombre VARCHAR(20) NOT NULL,
  tipoUno VARCHAR(10) NOT NULL,
  tipoDos VARCHAR(10) DEFAULT 'vacio',
  genero VARCHAR(6) DEFAULT 'hembra',
  descripcion VARCHAR(150) DEFAULT 'vacio',
  numeroEvolucion INT(1) NOT NULL,
  nivelEvolucion INT(3) NOT NULL,
  evoluciona VARCHAR(3) NOT NULL,
  nivel INT(3) DEFAULT 1,
  experiencia INT(3) DEFAULT 0,
  ContenedorExp INT(3) DEFAULT 5,
  hp INT(4) DEFAULT 100,
  hp_max INT(4) DEFAULT 100,
  ataque INT(4) DEFAULT 5,
  defensa INT(4) DEFAULT 5,
  ataque_especial INT(4) DEFAULT 5,
  defensa_especial INT(4) DEFAULT 5,
  velocidad INT(4) DEFAULT 5,
  estado VARCHAR(15) DEFAULT 'nada',
  IV INT(3) DEFAULT 31,
  EV INT(3) DEFAULT 254,
  capturado INT(10) DEFAULT 0,
  favorito VARCHAR(10) DEFAULT 0,
  ball VARCHAR(10) DEFAULT 'vacio');
  
CREATE TABLE IF NOT EXISTS sinnoh(
  numero_nacional VARCHAR(3) PRIMARY KEY NOT NULL,
  numero_regional VARCHAR(3) NOT NULL,
  region VARCHAR(20) NOT NULL,
  nombre VARCHAR(20) NOT NULL,
  tipoUno VARCHAR(10) NOT NULL,
  tipoDos VARCHAR(10) DEFAULT 'vacio',
  genero VARCHAR(6) DEFAULT 'hembra',
  descripcion VARCHAR(150) DEFAULT 'vacio',
  numeroEvolucion INT(1) NOT NULL,
  nivelEvolucion INT(3) NOT NULL,
  evoluciona VARCHAR(3) NOT NULL,
  nivel INT(3) DEFAULT 1,
  experiencia INT(3) DEFAULT 0,
  ContenedorExp INT(3) DEFAULT 5,
  hp INT(4) DEFAULT 100,
  hp_max INT(4) DEFAULT 100,
  ataque INT(4) DEFAULT 5,
  defensa INT(4) DEFAULT 5,
  ataque_especial INT(4) DEFAULT 5,
  defensa_especial INT(4) DEFAULT 5,
  velocidad INT(4) DEFAULT 5,
  estado VARCHAR(15) DEFAULT 'nada',
  IV INT(3) DEFAULT 31,
  EV INT(3) DEFAULT 254,
  capturado INT(10) DEFAULT 0,
  favorito VARCHAR(10) DEFAULT 0,
  ball VARCHAR(10) DEFAULT 'vacio');
  
CREATE TABLE IF NOT EXISTS teselia(
  numero_nacional VARCHAR(3) PRIMARY KEY NOT NULL,
  numero_regional VARCHAR(3) NOT NULL,
  region VARCHAR(20) NOT NULL,
  nombre VARCHAR(20) NOT NULL,
  tipoUno VARCHAR(10) NOT NULL,
  tipoDos VARCHAR(10) DEFAULT 'vacio',
  genero VARCHAR(6) DEFAULT 'hembra',
  descripcion VARCHAR(150) DEFAULT 'vacio',
  numeroEvolucion INT(1) NOT NULL,
  nivelEvolucion INT(3) NOT NULL,
  evoluciona VARCHAR(3) NOT NULL,
  nivel INT(3) DEFAULT 1,
  experiencia INT(3) DEFAULT 0,
  ContenedorExp INT(3) DEFAULT 5,
  hp INT(4) DEFAULT 100,
  hp_max INT(4) DEFAULT 100,
  ataque INT(4) DEFAULT 5,
  defensa INT(4) DEFAULT 5,
  ataque_especial INT(4) DEFAULT 5,
  defensa_especial INT(4) DEFAULT 5,
  velocidad INT(4) DEFAULT 5,
  estado VARCHAR(15) DEFAULT 'nada',
  IV INT(3) DEFAULT 31,
  EV INT(3) DEFAULT 254,
  capturado INT(10) DEFAULT 0,
  favorito VARCHAR(10) DEFAULT 0,
  ball VARCHAR(10) DEFAULT 'vacio');
  
CREATE TABLE IF NOT EXISTS kalos(
  numero_nacional VARCHAR(3) PRIMARY KEY NOT NULL,
  numero_regional VARCHAR(3) NOT NULL,
  region VARCHAR(20) NOT NULL,
  nombre VARCHAR(20) NOT NULL,
  tipoUno VARCHAR(10) NOT NULL,
  tipoDos VARCHAR(10) DEFAULT 'vacio',
  genero VARCHAR(6) DEFAULT 'hembra',
  descripcion VARCHAR(150) DEFAULT 'vacio',
  numeroEvolucion INT(1) NOT NULL,
  nivelEvolucion INT(3) NOT NULL,
  evoluciona VARCHAR(3) NOT NULL,
  nivel INT(3) DEFAULT 1,
  experiencia INT(3) DEFAULT 0,
  ContenedorExp INT(3) DEFAULT 5,
  hp INT(4) DEFAULT 100,
  hp_max INT(4) DEFAULT 100,
  ataque INT(4) DEFAULT 5,
  defensa INT(4) DEFAULT 5,
  ataque_especial INT(4) DEFAULT 5,
  defensa_especial INT(4) DEFAULT 5,
  velocidad INT(4) DEFAULT 5,
  estado VARCHAR(15) DEFAULT 'nada',
  IV INT(3) DEFAULT 31,
  EV INT(3) DEFAULT 254,
  capturado INT(10) DEFAULT 0,
  favorito VARCHAR(10) DEFAULT 0,
  ball VARCHAR(10) DEFAULT 'vacio');
  
CREATE TABLE IF NOT EXISTS alola(
  numero_nacional VARCHAR(3) PRIMARY KEY NOT NULL,
  numero_regional VARCHAR(3) NOT NULL,
  region VARCHAR(20) NOT NULL,
  nombre VARCHAR(20) NOT NULL,
  tipoUno VARCHAR(10) NOT NULL,
  tipoDos VARCHAR(10) DEFAULT 'vacio',
  genero VARCHAR(6) DEFAULT 'hembra',
  descripcion VARCHAR(150) DEFAULT 'vacio',
  numeroEvolucion INT(1) NOT NULL,
  nivelEvolucion INT(3) NOT NULL,
  evoluciona VARCHAR(3) NOT NULL,
  nivel INT(3) DEFAULT 1,
  experiencia INT(3) DEFAULT 0,
  ContenedorExp INT(3) DEFAULT 5,
  hp INT(4) DEFAULT 100,
  hp_max INT(4) DEFAULT 100,
  ataque INT(4) DEFAULT 5,
  defensa INT(4) DEFAULT 5,
  ataque_especial INT(4) DEFAULT 5,
  defensa_especial INT(4) DEFAULT 5,
  velocidad INT(4) DEFAULT 5,
  estado VARCHAR(15) DEFAULT 'nada',
  IV INT(3) DEFAULT 31,
  EV INT(3) DEFAULT 254,
  capturado INT(10) DEFAULT 0,
  favorito VARCHAR(10) DEFAULT 0,
  ball VARCHAR(10) DEFAULT 'vacio');
